---
- name: Search String with lineinfile
  hosts: localhost
  tasks:
    - name: "Searching for a String"
      lineinfile:
        path: /tmp/1.txt
        line: "new"
        state: present
      check_mode: yes
      register: presence

    - name: "print ouput"
      debug:
        msg: "{{presence}}"
